### ISSUE TITLE
Graphical fixes

### ISSUE THREAD

**Issue by psforscher** [rempsyc/busara_dashboard#31]
There are a couple miscellaneous graphical issues that I noticed. I'll mention them all here in a single issue.

- **Africa missing on the Continent, by Journal plot**. See below
<img width="651" alt="Screenshot 2024-03-18 at 00 26 57" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/0688a487-5678-409b-9ad3-3774d83b85e1">

- **Color scheme on the country by year graph**. There seem to be a bunch of duplicate colors on the plot
<img width="1381" alt="Screenshot 2024-03-18 at 00 25 00" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/0ce2d342-0862-4a99-b6a4-f3b2087d8cd6">

- **Axes on the by-year plots**. The axes are generally inconsistent across plots, and I think they should be consistent. Also, the economics axis has limits that exceed 0 and 100; anything less than 0 and greater than 100 is an impossible value
<img width="1396" alt="Screenshot 2024-03-18 at 00 28 42" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/6fc21dfb-3d05-47a0-8afd-eb9ba7f8db30">

- **Data for the economics by year plot**. I think the data are strange and might be buggy in this plot. For example, in the year 2016 all the papers are marked as coming from Europe, which seems unlikely given the data from the other years. I think this is worth a look (consult the figure above for reference)

**Comment by rempsyc** [comment]
As discussed today,
1. The missing continent for waffle plots I believe is a known issue with waffle plots for categories with little data. That said, it would be worth a more torough investigation again to document this behaviour properly.
2. The duplicate colours is due to our very high number of countries so R generates slightly different tones of the base colours meaning for a very large number, these colours are going to look pretty damn similar. It is possible to scroll to see all the different colours using the scrolling bar on the right.
3. For the axis, those could be fixed in a future upgrade.
4. For the strange data for economics journals, this is due to insufficient data for these data points, to be investigated in #34 indeed.

**Comment by rempsyc** [comment]
I am closing this as I have reorganized the problems into separate issues, as this is easier on my side to close each one with specific git commits and as they require different solutions with also different timelines.
