### ISSUE TITLE
Readiness for "soft launch" at SIPS 2024, June 10-12

### ISSUE THREAD

**Issue by psforscher** [rempsyc/busara_dashboard#33]
I'd like us to be prepared for a "soft launch" at the annual conference for the Society for the Improvement of Psychological Science, which [Busara is co-hosting](https://www.improvingpsych.org/SIPS2024/) this year in Nairobi on June 10-12.

To be prepared for a soft launch, I would like to accomplish the following:

- [x] Have a clear landing page
- [x] Be relatively user-friendly
- [x] Be clear about the limitations of the data (preferably by giving some indications of this on the graphs themselves)
- [x] Have a rough plan for the form of dissemination during the conference

**Comment by psforscher** [comment]
the improvements make a huge difference! just a couple comments on this version:

- the over-time tables and graphs look like they must be drawing on different versions of the data. for example, compare the graphs and tables below; in 2024 in the table, Africa is listed at 4.78%, but in the graph that percentage is 0

<img width="1020" alt="Screenshot 2024-05-20 at 14 39 01" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/04aa4f15-b80c-4b7e-b8dc-8a43be7b5a30">

<img width="1020" alt="Screenshot 2024-05-20 at 14 41 14" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/8ac8182b-77ad-4760-92f1-27322efd6608">

- there's a similar inconsistency between the graphical data and the data listed in the waffle plots (compare the over-time graph to the waffle plot below; Africa is listed as contributing 2% of data in the waffle plot, but in the over-time graph, there is no time-point where it has above 0% of the data)
<img width="871" alt="Screenshot 2024-05-20 at 14 44 39" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/e25ab042-54ef-4b3c-9b50-6f8ba5c3673e">

**Comment by rempsyc** [comment]
> just a couple comments on this version:

Good catch, thanks! I opened an issue in #47.

**Comment by psforscher** [comment]
> One issue I have also is that I fear behavioural science only represents a fraction of all Nature, Science, PNAS, and PloS One papers, so I don't know if we can legitimately use these data to make claims about behavioural science as a whole since because of their volume, these general journals overwhelm the rest of the data by a factor of 5, so the "All fields" page and gauges are misleading.

good point. i think for now the landing page should just draw from psych and economics and the "general" page should make clear that it's not behavioral science, but rather some general-interest journals. after SIPS, maybe you can look at using the openalex codes to filter the non-behavioral-science.

> Yeah I think in the end I am too busy to fly there in person and also I was thinking that is probably a lot of money for the benefits, which would probably be better spent locally or in more dashboard development :)

> Because of my schedule, I'm afraid even an online presentation would not really work for me in the current timing :(

> Would you be ok to present it with option 2? If you can't, then I could try to make it work for option 1 (online presentation), and I think option 3 can be done anyhow now, as I feel much more comfortable with the openAlex data :)

yes, i'm happy to do option 2 and to do a social media release. :)

**Comment by rempsyc** [comment]
> i think for now the landing page should just draw from psych and economics and the "general" page should make clear that it's not behavioral science, but rather some general-interest journals. 

If we decide not to go ahead with already using keywords as in #48, having the landing page just from psych and econ would bring up an additional question: Would the "All fields" be meaningful at all? If they are meant to be compared, not be aggregated, especially since the subfields get "erased" by the differential ratio of papers, should I remove the combined panel with all the data?

Or should "All fields" be kept but only include economics and psychology? Lastly, behavioural science is less homogenous than its composite fields. Does it even make sense to combine economic and psychology together if they clearly belong to different populations? Aren't we hiding the real data patterns doing so?

**Comment by psforscher** [comment]
hmm now that i see the new header labels, i've changed my mind again -- lol!

i see now that the longer labels are making the header run off the screen awkwardly on my laptop, and in addition, "Behavioral Science Journals" to me seems to imply that the set of journals is different rather than the combination of Psychology and Economics.

<img width="1420" alt="Screenshot 2024-05-21 at 11 05 25" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/d78a1024-c3d6-40b4-a27c-65a208e2c25a">

maybe we can change these again to "Economics + Psychology", "Psychology", "Economics", and "General Interest"? this way, they don't run off the page, and it's clearer what goes into what used to be called "Behavioral Science". people can get a sense of why we group together economics and psychology based on how we describe behavioral science on the landing page.

**Comment by rempsyc** [comment]
> "Behavioral Science Journals" to me seems to imply that the set of journals is different rather than the combination of Psychology and Economics. ... maybe we can change these again to "Economics + Psychology"

Exacly what I was thinking ;)

Also, do we need the instructions page anymore if _every_ page basically has the full instructions? 🤔

**Comment by psforscher** [comment]
ah, good point. do you feel that all the content on the instructions page is replicated elsewhere? if so, i say delete the instructions page

**Comment by psforscher** [comment]
i like the instructions as-is. i suppose this is something we can get feedback on during the soft launch, though. for now, let's keep them and see how people react?

**Comment by rempsyc** [comment]
Seems like the `flexdashboard` navigation menu [cannot](https://stackoverflow.com/questions/72229723/how-to-escape-single-quote-in-flexdashboard-navbar-menu) accept special characteres like`+` or `&`, so I have to use `Economics and Psychology` instead.

**Comment by psforscher** [comment]
the current instructions (were they expanded?) seem to be overflowing the right side-bar. maybe they can be revised as follows:

> The scatter plots use the [plotly](https://plotly.com/r/) package, which converts regular images into interactive web graphics. Here are some tips to make the most of plotly figures.
>
> When you hover over a plotly figure, you will see a menu appear on the top-right of the figure. This is called the [Chart Studio Modebar](https://plotly.com/chart-studio-help/getting-to-know-the-plotly-modebar/). Some of these options include: (a) Download Plot as a PNG; (b) Zoom and Pan Buttons; (c) Zoom In/Out; (d) Autoscale and Reset Axes; and (e) Hover Options.
>
> Interacting With Data Points and Legend Groupings
>
> 1. When hovering over individual data points, you can see the raw data.
> 2. When hovering over the regression line, you can see the predicted data
> 3. Click, hold, and drag to zoom into a specific window of the chart. Double-click anywhere to come back to the original zoom level.
> 4. Double-clicking on one line will isolate it. Double-clicking again will discontinue the isolation.
> 5. Single-clicking on a line will remove that category. Clicking again will bring it back
> 6. When the legend is too long, use the scroll bar to see the rest of it

**Comment by psforscher** [comment]
here's a simplification for the table instructions:

> All tables use the [DT](https://rstudio.github.io/DT/) package, which converts regular dataframes into interactive HTML table widgets. Here are some tips to make the most of these tables.
>
> 1. You can click on the top left to change the number of entries to show
> 2. You can change page by clicking on the bottom right area
> 3. You can sort by column by clicking on the column of your choice
> 4. You can search for specific values (for example journals or countries) by using the search bar at the top-right

**Comment by psforscher** [comment]
one more minor one -- in the top bar, change "Economics and Psychology" to "Psychology and Economics" to match the order of the menus in the top-bar

**Comment by rempsyc** [comment]
> the current instructions (were they expanded?)

Yes, I expended them a little bit trying to fit all the instructions on it to get rid of the instructions page. I will go with your suggestions for changing instructions but just for future reference, I can only specify the size of the panels in absolute units, so screen size unfortunately will always matter a lot for these things. For example, this is how I see it on my screen (so I thought it was ok):

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/f36f05b9-ced5-493b-9ef4-bc0dcc41031b)

But if I zoom to simulate a smaller screen, then I see what you mean:

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/45fba0a2-0c51-40a1-9bb7-11dc1fdc2f18)

I suppose the best is that it works on smaller screens first since on bigger screens it will also naturally fit (if only adding more white space).

**Comment by rempsyc** [comment]
> maybe they can be revised as follows:

Thanks, those are great suggestions, I like it. Shorter is better! I've kept some of the old stuff though, I hope that's fine. Now though it will hopefully fit most screens.

**Comment by psforscher** [comment]
![image](https://github.com/rempsyc/busara_dashboard/assets/149572347/8478949b-7630-45f3-8b5f-b57295f8a1c1)

seems like there's a bug here

**Comment by psforscher** [comment]
seems to affect all country waffle plots

![image](https://github.com/rempsyc/busara_dashboard/assets/149572347/fe92df6b-6040-4cca-b12a-3927b24e5eff)

**Comment by rempsyc** [comment]
Damn! That's because of my recent change for keeping the top 5 and clustering all the rest as the "Other" category. Unfortunately I won't have time to fix it until I come back I'm afraid!

**Comment by psforscher** [comment]
ok! the other graphs work though! enjoy your vacation <3

**Comment by rempsyc** [comment]
Updated waffle from your previous screenshot:

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/7349a32e-ad52-4cd6-9be8-07ebe2ac372a)

I changed the previous rule of only showing countries in the legend that had a high enough percentage because that still resulting in too many countries in the legend (the colour palette only has 8 colours so that's kind of the hard limit for number of countries). The new rule then only takes the top 8 countries globally.

This is why for example if you look at the economics journals:

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/e55d92aa-5a8f-4a65-bb89-79a5cc482f11)

You have some waffles that are almost entirely empty (like ADR, AJARE, and AJEMS). This is because that journal has more countries outside than inside the overall top 8 countries. This can create bias for example because small journals are less likely to pull their weight on the selection of the top 8 since they report fewer articles, and so if the countries are more diverse, this is less likely to show.

This is kind of a visualization challenge and I'd be happy to get your thoughts on it.

**Comment by rempsyc** [comment]
Another possiblity to better report small percentages is to have more than 100 squares, so you can better represent fractions like for the Global South continents. Here's an example for what I mean: https://github.com/haghish/shapley/blob/master/man/figures/waffle.png

So e.g., each square could represent .20% instead of 1%. But I am not so sure about it, it is harder to explain when communicating to a general audience. But just wanted to share this option.

**Comment by psforscher** [comment]
not what to do about the color pallette issue, but an easy fix to having empty squares is to add another category called "Another country" and populate the waffle plots with that

**Comment by rempsyc** [comment]
Oh true, this is what we used to do!

**Comment by rempsyc** [comment]
> the "About" sidebar

Corrected, thanks!

**Comment by rempsyc** [comment]
> having empty squares is to add another category called "Another country"

I'm going to try the same principle for the scatter plot by country also

**Comment by rempsyc** [comment]
The strategy to add a category "Other" for other countries does not work with the waffle plots using country flags because no flag can be identified with country name "Other", so it is not plotted.

**Comment by rempsyc** [comment]
Ok. A little update for each panel:
1. Continent: OK
2. Continent, by Year: OK
3. Continent, by Journal: OK
4. Country: OK. I changed it so that the graph matched the table values, using full country names and getting rid of the legend title, and having the other countries as NA so it appears empty (best workaround for our problem)
5. Country, by Year: OK (added eigth country cumulative "Other")
6. Country, by Journal: OK (added eigth country cumulative "Other")

**Comment by psforscher** [comment]
looks great. we have the dashboard scheduled in the Busara SIPS social media campaign on June 4. i'll also be doing my own posting about the dashboard on the same day on both LinkedIn and Bluesky. finally, i plan to do a pop-up session about a few CREME projects during SIPS, with a strong focus on the dashboard. so i think we have some decent initial dissemination planned!

**Comment by psforscher** [comment]
did i mention already that i am SO STOKED about this dashboard??? lol. truly, it already surpasses my wildest imaginings for what this project could have become.

some time after initial dissemination, i'd like to send the dashboard to a select few journal editors to see how they react to it. journal editors were my original targets for change. i'm open to your feedback about how comfortable you are with this, but i think we have a product we can show to at least a few of these

**Comment by psforscher** [comment]
update on dissemination plans: the busara social media team is pretty overloaded during SIPS, so i've been advised that it might make more sense to do the big social media push in august rather than in june. given that information, what i might do is do some soft promotion of the dashboard (through a talk) during SIPS and delay the big push at dissemination until around august.

does that plan sound reasonable to you as well?

**Comment by rempsyc** [comment]
> update on dissemination plans: the busara social media team is pretty overloaded during SIPS, so i've been advised that it might make more sense to do the big social media push in august rather than in june. given that information, what i might do is do some soft promotion of the dashboard (through a talk) during SIPS and delay the big push at dissemination until around august. does that plan sound reasonable to you as well?

Yes, sounds reasonable.

> did i mention already that i am SO STOKED about this dashboard??? lol. truly, it already surpasses my wildest imaginings for what this project could have become.

Thank you for partnering with me to make this dream come true 💙🌈

> some time after initial dissemination, i'd like to send the dashboard to a select few journal editors to see how they react to it. journal editors were my original targets for change. i'm open to your feedback about how comfortable you are with this, but i think we have a product we can show to at least a few of these

That's OK, I think we have an Alpha Version 1.0 that we can stand behind now that we rely on OpenAlex. Of course, there is still MUCH work to be done, e.g., showing numbers by capita, which I'm sure we will hear again and again. There are also still many comments from the original round of review which I haven't finished addressing yet...

**Comment by rempsyc** [comment]
Closing this issue now that SIPS 2024 is over
